import type { VenueData, LayoutData, FloorObject, LiveUser } from "@/types";

export const DEMO_VENUE: VenueData = {
  id: "venue-grand-ballroom",
  name: "Grand Ballroom",
  address: "123 Event Plaza, San Francisco, CA",
  capacity: 500,
  rooms: [
    { id: "room-main-hall", name: "Main Hall", width: 20, height: 15, capacity: 300 },
    { id: "room-patio", name: "Patio", width: 12, height: 8, capacity: 80 },
    { id: "room-vip", name: "VIP Room", width: 8, height: 6, capacity: 40 },
    { id: "room-lobby", name: "Lobby", width: 10, height: 6, capacity: 80 },
  ],
};

export const DEMO_WEDDING_OBJECTS: FloorObject[] = [
  {
    id: "obj-stage",
    itemName: "Stage",
    itemType: "stage",
    category: "EQUIPMENT",
    x: 7,
    y: 1,
    width: 4,
    height: 2.5,
    rotation: 0,
    locked: false,
    color: "#2D3748",
  },
  {
    id: "obj-dance",
    itemName: "Dance Floor",
    itemType: "dance-floor",
    category: "EQUIPMENT",
    x: 6,
    y: 5,
    width: 4,
    height: 4,
    rotation: 0,
    locked: false,
    color: "#2B6CB0",
  },
  {
    id: "obj-bar",
    itemName: "Bar",
    itemType: "bar",
    category: "EQUIPMENT",
    x: 16,
    y: 2,
    width: 3,
    height: 0.8,
    rotation: 0,
    locked: false,
    color: "#744210",
  },
  {
    id: "obj-table-1",
    itemName: "Round Table (60\")",
    itemType: "round-table-60",
    category: "TABLES",
    x: 2,
    y: 4,
    width: 1.5,
    height: 1.5,
    rotation: 0,
    locked: false,
    color: "#8B7355",
    capacity: 8,
  },
  {
    id: "obj-table-2",
    itemName: "Round Table (60\")",
    itemType: "round-table-60",
    category: "TABLES",
    x: 2,
    y: 8,
    width: 1.5,
    height: 1.5,
    rotation: 0,
    locked: false,
    color: "#8B7355",
    capacity: 8,
  },
  {
    id: "obj-table-3",
    itemName: "Round Table (72\")",
    itemType: "round-table-72",
    category: "TABLES",
    x: 14,
    y: 8,
    width: 1.8,
    height: 1.8,
    rotation: 0,
    locked: false,
    color: "#8B7355",
    capacity: 10,
  },
  {
    id: "obj-table-4",
    itemName: "Round Table (60\")",
    itemType: "round-table-60",
    category: "TABLES",
    x: 14,
    y: 4,
    width: 1.5,
    height: 1.5,
    rotation: 0,
    locked: false,
    color: "#8B7355",
    capacity: 8,
  },
  {
    id: "obj-dj",
    itemName: "DJ Booth",
    itemType: "dj-booth",
    category: "EQUIPMENT",
    x: 12,
    y: 1.5,
    width: 2,
    height: 1,
    rotation: 0,
    locked: false,
    color: "#1A202C",
  },
];

export const DEMO_LAYOUT: LayoutData = {
  id: "layout-wedding",
  name: "Wedding Setup",
  description: "Standard wedding reception layout",
  roomId: "room-main-hall",
  venueId: "venue-grand-ballroom",
  objects: DEMO_WEDDING_OBJECTS,
  version: 3,
};

export const DEMO_LIVE_USERS: LiveUser[] = [
  { id: "user-sarah", name: "Sarah", status: "editing", color: "#4c6ef5" },
  { id: "user-mike", name: "Mike", status: "editing", color: "#22c55e" },
  { id: "user-john", name: "John", status: "viewing", color: "#f59e0b" },
];
