import type { VenueData, LayoutData, FloorObject, LiveUser } from "@/types";

export const TRS_VENUE_ID = "venue-the-rink-studios";

export const DEMO_VENUE: VenueData = {
  id: TRS_VENUE_ID,
  name: "The Rink Studios",
  address: "The Rink Studios",
  capacity: 400,
  rooms: [
    { id: "room-main-rink", name: "Main Rink", width: 30, height: 20, capacity: 250 },
    { id: "room-studio-floor", name: "Studio Floor", width: 15, height: 12, capacity: 80 },
    { id: "room-concessions", name: "Concessions", width: 10, height: 6, capacity: 40 },
    { id: "room-party-room", name: "Party Room", width: 8, height: 6, capacity: 30 },
  ],
};

export const DEMO_EVENT_OBJECTS: FloorObject[] = [
  {
    id: "obj-stage",
    itemName: "Stage",
    itemType: "stage",
    category: "EQUIPMENT",
    x: 10,
    y: 1,
    width: 6,
    height: 3,
    rotation: 0,
    locked: false,
    color: "#2D3748",
  },
  {
    id: "obj-dance",
    itemName: "Dance Floor",
    itemType: "dance-floor",
    category: "EQUIPMENT",
    x: 9,
    y: 8,
    width: 8,
    height: 6,
    rotation: 0,
    locked: false,
    color: "#2B6CB0",
  },
  {
    id: "obj-bar",
    itemName: "Bar",
    itemType: "bar",
    category: "EQUIPMENT",
    x: 24,
    y: 2,
    width: 4,
    height: 0.8,
    rotation: 0,
    locked: false,
    color: "#744210",
  },
  {
    id: "obj-table-1",
    itemName: "Round Table (60\")",
    itemType: "round-table-60",
    category: "TABLES",
    x: 2,
    y: 5,
    width: 1.5,
    height: 1.5,
    rotation: 0,
    locked: false,
    color: "#8B7355",
    capacity: 8,
  },
  {
    id: "obj-table-2",
    itemName: "Round Table (60\")",
    itemType: "round-table-60",
    category: "TABLES",
    x: 2,
    y: 10,
    width: 1.5,
    height: 1.5,
    rotation: 0,
    locked: false,
    color: "#8B7355",
    capacity: 8,
  },
  {
    id: "obj-table-3",
    itemName: "Cocktail Table",
    itemType: "cocktail-table",
    category: "TABLES",
    x: 22,
    y: 10,
    width: 0.6,
    height: 0.6,
    rotation: 0,
    locked: false,
    color: "#C4A882",
    capacity: 4,
  },
  {
    id: "obj-dj",
    itemName: "DJ Booth",
    itemType: "dj-booth",
    category: "EQUIPMENT",
    x: 18,
    y: 1.5,
    width: 2,
    height: 1,
    rotation: 0,
    locked: false,
    color: "#1A202C",
  },
];

export const DEMO_LAYOUT: LayoutData = {
  id: "layout-concert-on-ice",
  name: "Concert on Ice",
  description: "Stage, dance floor, and concessions layout for Main Rink",
  roomId: "room-main-rink",
  venueId: TRS_VENUE_ID,
  objects: DEMO_EVENT_OBJECTS,
  version: 3,
};

export const DEMO_LIVE_USERS: LiveUser[] = [
  { id: "user-sarah", name: "Sarah", status: "editing", color: "#4c6ef5" },
  { id: "user-mike", name: "Mike", status: "editing", color: "#22c55e" },
  { id: "user-john", name: "John", status: "viewing", color: "#f59e0b" },
];
